---
nav_order: 0
title: OpenAIRepository.ts
parent: repositories
---

# OpenAIRepository.ts

This TypeScript file defines a class called `OpenAIRepository` that provides methods to interact with the OpenAI API. The class is responsible for querying the OpenAI API and handling the responses.

## Class: OpenAIRepository

### Constructor

The constructor initializes the `OpenAIApi` instance with the API key from the `ConfigHelper`.

### Methods

#### query(text: string): Promise<OpenAIResponse>

This method takes a single question as a string and returns a Promise that resolves to an `OpenAIResponse` object. It internally calls the `queryQuestions` method with the single question.

Example:

```typescript
const openAIRepo = new OpenAIRepository();
openAIRepo.query("What is the capital of France?").then((response) => {
  console.log(response.answer);
});
```

#### queryQuestions(questions: string[], errorCount = 0, model?: string, assistantMessages?: string[]): Promise<OpenAIResponse>

This method takes an array of questions, an optional error count, an optional model, and an optional array of assistant messages. It returns a Promise that resolves to an `OpenAIResponse` object.

The method constructs a series of messages, including system commands, user questions, and assistant messages, and sends them to the OpenAI API. It handles errors and retries if necessary.

Example:

```typescript
const openAIRepo = new OpenAIRepository();
openAIRepo
  .queryQuestions(["What is the capital of France?", "What is the capital of Germany?"])
  .then((response) => {
    console.log(response.answer);
  });
```

### Error Handling

The `queryQuestions` method handles various error scenarios, such as exceeding the quota, retrying on specific HTTP status codes, and logging errors.

## Models

### OpenAIResponse

This interface represents the response from the OpenAI API. It contains the following properties:

- `answer`: The answer generated by the OpenAI API.
- `requestMessages`: The array of messages sent to the OpenAI API.

## Configuration and Helper Classes

- `ConfigHelper`: A helper class that provides access to the configuration settings, such as the OpenAI API key and GPT model.
- `Configuration`: A class from the `openai` package that is used to configure the OpenAI API instance.
- `OpenAIApi`: A class from the `openai` package that provides methods to interact with the OpenAI API.

## Dependencies

- `openai`: The package that provides the OpenAI API client.
- `timers/promises`: A package that provides the `setTimeout` function for promises.